import React from 'react';
import { Container, Grid, GridCol, Card, Text, Stack, Button, Badge, Group } from '@mantine/core';
import PageHeader from '../components/common/PageHeader';
import { getPayload } from 'payload';
import config from '@payload-config';

// This will be generated by Payload
interface Service {
  id: string;
  name: string;
  description: any; // Rich text content
  price: number;
  currency: string;
  duration: number;
  type: 'private' | 'group' | 'workshop';
  image?: any;
  isActive: boolean;
  maxParticipants?: number;
}

async function getServices(): Promise<Service[]> {
  try {
    const payload = await getPayload({
      config,
    });

    const services = await payload.find({
      collection: 'services',
      where: {
        isActive: {
          equals: true,
        },
      },
      limit: 20,
      sort: '-createdAt',
    });

    return services.docs;
  } catch (error) {
    console.error('Error fetching services:', error);
    return [];
  }
}

const typeColors = {
  private: 'blue',
  group: 'green', 
  workshop: 'orange',
};

const typeLabels = {
  private: 'Private Session',
  group: 'Group Class',
  workshop: 'Workshop',
};

export default async function ServicesPage() {
  const services = await getServices();

  return (
    <>
      <PageHeader 
        title="Our Services" 
        subtitle="Professional dog training services tailored to you and your pet's needs."
      />
      
      <Container size="lg" pb={80}>
        {services.length === 0 ? (
          <Text ta="center" size="lg" c="gray.7" mt="xl">
            No services available at the moment. Please check back later.
          </Text>
        ) : (
          <Grid>
            {services.map((service) => (
              <GridCol key={service.id} span={{ base: 12, md: 6, lg: 4 }}>
                <Card shadow="md" radius="md" h="100%" p="lg">
                  <Stack gap="md" h="100%">
                    <Group justify="space-between">
                      <Badge color={typeColors[service.type]} variant="filled">
                        {typeLabels[service.type]}
                      </Badge>
                      <Text size="xl" fw={700} c="primary.9">
                        £{service.price}
                      </Text>
                    </Group>

                    <Stack gap="xs" style={{ flex: 1 }}>
                      <Text size="lg" fw={600} c="gray.8">
                        {service.name}
                      </Text>
                      
                      <Text size="sm" c="gray.6">
                        Duration: {service.duration} minutes
                      </Text>

                      {service.maxParticipants && (
                        <Text size="sm" c="gray.6">
                          Max participants: {service.maxParticipants}
                        </Text>
                      )}

                      <Text size="sm" c="gray.7" mt="sm">
                        {typeof service.description === 'string' 
                          ? service.description 
                          : 'Professional training service tailored to your needs.'}
                      </Text>
                    </Stack>

                    <Button 
                      variant="filled" 
                      color="primary" 
                      fullWidth
                      mt="auto"
                    >
                      Book Now
                    </Button>
                  </Stack>
                </Card>
              </GridCol>
            ))}
          </Grid>
        )}
      </Container>
    </>
  );
}